# Generated by tools/wp2pelican.py -- do not edit by hand.
# Slug substitutions run after pelican's defaults (see pelicanconf.py), so
# categories/tags/authors keep the exact slugs WordPress used in URLs.
WP_CATEGORY_SUBS = [('^video$', 'media'), ('^interviu$', 'interview'), ('^novosti$', 'news'), ('^obzory\\-albomov$', 'review'), ('^podkasty$', 'podcast'), ('^radioshou\\-grani$', 'podcast/grani-podcast'), ('^raznoe$', 'misc'), ('^reportazhi$', 'reports'), ('^sobytiia$', 'events'), ('^treki$', 'tracks'), ('^ia_like$', 'podcast/i_like')]
WP_TAG_SUBS = [('^berlinschool$', 'berlin-school'), ('^recordbox$', 'record-box'), ('^rhythmnoise$', 'rhythmnnoise')]
WP_AUTHOR_SUBS = [('^heavy\\-seas$', 'djevilhero'), ('^quarck$', 'admin'), ('^nik\\-zavriev$', 'organickloud')]
WP_MENUITEMS = [('Архив', '/content/'), ('О сайте', '/about/')]
